/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.9/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "Modula2Java17-Tests"
//include("app")

include(":Modula2Java17")
project(":Modula2Java17").projectDir = File("../../Modula2Java17/Modula2Java17")

include(":Modula2-Runtime")
project(":Modula2-Runtime").projectDir = File("../../Modula2Java17/Modula2-Runtime")
